:toc: center
:backend: pdf
:doctitle: Cukedoctor Documentation
:doctype: book
:icons: font
:numbered:
:sectanchors:
:sectlink:
:docinfo:
:source-highlighter: coderay
:toclevels: 3
:revnumber: 3.9.0
:hardbreaks:
:chapter-label: Chapter
:version-label: Version
:allow-uri-read:

= *Cukedoctor Documentation*

include::/home/runner/work/cukedoctor/cukedoctor/cukedoctor-converter/target/test-classes/cukedoctor-intro.adoc[leveloffset=+1]


== *Features*

[[Cukedoctor-Converter, Cukedoctor Converter]]
=== *Cukedoctor Converter*

****
====
[quote]
____
In order to have awesome _living documentation_
As a bdd developer
I want to use *Cukedoctor* to convert my cucumber test results into `readable` living documentation.
____
====
****

==== Convert features test output into documentation

==========
Given ::
The following two features: icon:thumbs-up[role="green",title="Passed"]
----

Feature: Feature1

  Scenario: Scenario feature 1

    Given scenario step

Feature: Feature2

  Scenario: Scenario feature 2

    Given scenario step

----
When ::
I convert their json test output using cukedoctor converter icon:thumbs-up[role="green",title="Passed"]
******

[discrete]
[IMPORTANT]
=======
[discrete]
To generate cucumber .json output files just execute your _BDD_ tests with *json* formatter, example:
[discrete]
[discrete]
[source,java]
----
@RunWith(Cucumber.class)
@CucumberOptions(plugin = {"json:target/cucumber.json"} )
----
[discrete]
NOTE: *plugin* option replaced *format* option which was deprecated in newer cucumber versions.
[discrete]
=======


******
Then ::
I should have awesome living documentation icon:thumbs-up[role="green",title="Passed"]
******

[discrete]
[discrete]
= *Documentation*
[discrete]
[discrete]
[discrete]
[discrete]
== *Summary*
[discrete]
[cols="12*^m", options="header,footer"]
[discrete]
|===
3+|Scenarios 7+|Steps 2+|Features: 2
|[green]#*Passed*#
|[red]#*Failed*#
|Total
|[green]#*Passed*#
|[red]#*Failed*#
|[purple]#*Skipped*#
|[maroon]#*Pending*#
|[yellow]#*Undefined*#
|[blue]#*Missing*#
|Total
|Duration
|Status
12+^|*<<Feature1>>*
|1
|0
|1
|1
|0
|0
|0
|0
|0
|1
|647ms
|[green]#*passed*#
12+^|*<<Feature2>>*
|1
|0
|1
|1
|0
|0
|0
|0
|0
|1
|000ms
|[green]#*passed*#
12+^|*Totals*
|2|0|2|2|0|0|0|0|0|2 2+|647ms
|===
[discrete]
[discrete]
== *Features*
[discrete]
[discrete]
[[Feature1, Feature1]]
[discrete]
=== *Feature1*
[discrete]
[discrete]
==== Scenario: Scenario feature 1
[discrete]
============
[discrete]
Given ::
[discrete]
scenario step icon:thumbs-up[role="green",title="Passed"] [small right]#(647ms)#
============
[discrete]
[discrete]
[[Feature2, Feature2]]
[discrete]
=== *Feature2*
[discrete]
[discrete]
==== Scenario: Scenario feature 2
[discrete]
============
[discrete]
Given ::
[discrete]
scenario step icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
============


******
==========

[[Ordering, Ordering]]
=== *Ordering*

****
====
[quote]
____
In order to have features ordered in living documentation
As a bdd developer
I want to control the order of features in my documentation
____
====
****

==== Default ordering

==========
Given ::
The following two features: icon:thumbs-up[role="green",title="Passed"]
----

Feature: Feature1

  Scenario: Scenario feature 1

    Given scenario step

Feature: Feature2

  Scenario: Scenario feature 2

    Given scenario step

----
When ::
I convert them using default order icon:thumbs-up[role="green",title="Passed"]
Then ::
Features should be ordered by name in resulting documentation icon:thumbs-up[role="green",title="Passed"]
******

[discrete]
== *Features*
[discrete]
[discrete]
[[Feature1, Feature1]]
[discrete]
=== *Feature1*
[discrete]
[discrete]
==== Scenario: Scenario feature 1
[discrete]
============
[discrete]
Given ::
[discrete]
scenario step icon:thumbs-up[role="green",title="Passed"] [small right]#(647ms)#
============
[discrete]
[discrete]
[[Feature2, Feature2]]
[discrete]
=== *Feature2*
[discrete]
[discrete]
==== Scenario: Scenario feature 2
[discrete]
============
[discrete]
Given ::
[discrete]
scenario step icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
============


******
==========

==== Custom ordering with tags
NOTE: Ordering is done using feature tag *@order-*

==========
Given ::
The following two features: icon:thumbs-up[role="green",title="Passed"]
----

@order-2
Feature: Feature1

  Scenario: Scenario feature 1

    Given scenario step

@order-1
Feature: Feature2

  Scenario: Scenario feature 2

    Given scenario step

----
When ::
I convert them using tag order icon:thumbs-up[role="green",title="Passed"]
Then ::
Features should be ordered respecting order tag icon:thumbs-up[role="green",title="Passed"]
******

[discrete]
== *Features*
[discrete]
[discrete]
[[Feature2, Feature2]]
[discrete]
=== *Feature2*
[discrete]
[discrete]
==== Scenario: Scenario feature 2
[discrete]
============
[discrete]
Given ::
[discrete]
scenario step icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
============
[discrete]
[discrete]
[[Feature1, Feature1]]
[discrete]
=== *Feature1*
[discrete]
[discrete]
==== Scenario: Scenario feature 1
[discrete]
============
[discrete]
Given ::
[discrete]
scenario step icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
============


******
==========

[[Enrich-features, Enrich features]]
=== *Enrich features*

****
====
[quote]
____
In order to have awesome _living documentation_
As a bdd developer
I want to render asciidoc markup inside my features.
____
====

https://asciidoctor.org/docs/what-is-asciidoc/[Asciidoc^] markup can be used in feature *DocStrings*. To do so you can enable it by using *@asciidoc* tag at `feature` or `scenario` level.

[IMPORTANT]
=====
Adding @asciidoc tag at *feature level* will make cukedoctor interpret `all features docstrings` as Asciidoc markup.

Adding @asciidoc at *scenario level* will make cukedoctor interpret `all steps docstrings` as asciidoc markup.

TIP: To enable asciidoc markup in a *single step* you can use `asciidoc` as https://relishapp.com/cucumber/cucumber/docs/gherkin/doc-strings#docstring-with-interesting-content-type[docstring content type^].
=====

NOTE: Feature and scenario descriptions are automatically interpreted as Asciidoc markup without the need for adding the feature tag.
****

==== DocString enrichment activated by the content type
Asciidoc markup can be used in feature *DocStrings*. To do so you can enable it by using the content type *[asciidoc]* in the DocString.

==========
Given ::
The following two features: icon:thumbs-up[role="green",title="Passed"]
----

Feature: Discrete class feature

  Scenario: Render source code

    Given the following source code in docstrings
"""asciidoc
  [source, java]
  -----
  public int sum(int x, int y){
  int result = x + y;
  return result; (1)
  }
  -----
  <1> We can have callouts in living documentation
"""

  Scenario: Render table

    Given the following table
 """asciidoc
  |===

  | Cell in column 1, row 1 | Cell in column 2, row 1
  | Cell in column 1, row 2 | Cell in column 2, row 2
  | Cell in column 1, row 3 | Cell in column 2, row 3

  |===
"""

----
When ::
I convert enriched docstring with asciidoc content type using cukedoctor converter icon:thumbs-up[role="green",title="Passed"]
Then ::
DocString asciidoc output must be rendered in my documentation icon:thumbs-up[role="green",title="Passed"]
******

[discrete]
== *Features*
[discrete]
[discrete]
[[Discrete-class-feature, Discrete class feature]]
[discrete]
=== *Discrete class feature*
[discrete]
[discrete]
==== Scenario: Render source code
[discrete]
============
[discrete]
Given ::
[discrete]
the following source code in docstrings icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
[discrete]
*******
[discrete]
[discrete]
[discrete]
[discrete]
[source, java]
-----
public int sum(int x, int y){
    int result = x + y;
    return result; (1)
}
-----
[discrete]
[discrete]
[discrete]
<1> We can have callouts in living documentation
[discrete]
[discrete]
[discrete]
*******
============
[discrete]
[discrete]
==== Scenario: Render table
[discrete]
============
[discrete]
Given ::
[discrete]
the following table icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
[discrete]
*******
[discrete]
[discrete]
[discrete]
[discrete]
|===
| Cell in column 1, row 1 | Cell in column 2, row 1
| Cell in column 1, row 2 | Cell in column 2, row 2
| Cell in column 1, row 3 | Cell in column 2, row 3
|===
[discrete]
[discrete]
[discrete]
*******
============


******
==========

==== DocString enrichment activated by a feature tag
Asciidoc markup can be used in feature *DocStrings*. You can enable this by applying the tag [@asciidoc] to the feature. Note this enables the enrichment for all DocStrings within the feature.

==========
Given ::
The following two features: icon:thumbs-up[role="green",title="Passed"]
----

@asciidoc
Feature: Discrete class feature

  Scenario: Render source code

    Given the following source code in docstrings
"""
  [source, java]
  -----
  public int sum(int x, int y){
  int result = x + y;
  return result; (1)
  }
  -----
  <1> We can have callouts in living documentation
"""

  Scenario: Render table

    Given the following table
 """
  |===

  | Cell in column 1, row 1 | Cell in column 2, row 1
  | Cell in column 1, row 2 | Cell in column 2, row 2
  | Cell in column 1, row 3 | Cell in column 2, row 3

  |===
"""

----
When ::
I convert enriched docstring with asciidoc feature tag using cukedoctor converter icon:thumbs-up[role="green",title="Passed"]
Then ::
DocString asciidoc output must be rendered in my documentation icon:thumbs-up[role="green",title="Passed"]
******

[discrete]
== *Features*
[discrete]
[discrete]
[[Discrete-class-feature, Discrete class feature]]
[discrete]
=== *Discrete class feature*
[discrete]
[discrete]
==== Scenario: Render source code
[discrete]
============
[discrete]
Given ::
[discrete]
the following source code in docstrings icon:thumbs-up[role="green",title="Passed"] [small right]#(011ms)#
[discrete]
*******
[discrete]
[discrete]
[discrete]
[discrete]
[source, java]
-----
public int sum(int x, int y){
    int result = x + y;
    return result; (1)
}
-----
[discrete]
[discrete]
[discrete]
<1> We can have callouts in living documentation
[discrete]
[discrete]
[discrete]
*******
============
[discrete]
[discrete]
==== Scenario: Render table
[discrete]
============
[discrete]
Given ::
[discrete]
the following table icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
[discrete]
*******
[discrete]
[discrete]
[discrete]
[discrete]
|===
| Cell in column 1, row 1 | Cell in column 2, row 1
| Cell in column 1, row 2 | Cell in column 2, row 2
| Cell in column 1, row 3 | Cell in column 2, row 3
|===
[discrete]
[discrete]
[discrete]
*******
============


******
==========

==== DocString enrichment activated by a scenario tag
Asciidoc markup can be used in feature *DocStrings*. You can enable this by applying the tag [@asciidoc] to the scenario. Note this enables the enrichment for all DocStrings within the scenario.

==========
Given ::
The following two features: icon:thumbs-up[role="green",title="Passed"]
----

Feature: Discrete class feature

  @asciidoc
  Scenario: Render source code

    Given the following source code in docstrings
"""
  [source, java]
  -----
  public int sum(int x, int y){
  int result = x + y;
  return result; (1)
  }
  -----
  <1> We can have callouts in living documentation
"""

  @asciidoc
  Scenario: Render table

    Given the following table
 """
  |===

  | Cell in column 1, row 1 | Cell in column 2, row 1
  | Cell in column 1, row 2 | Cell in column 2, row 2
  | Cell in column 1, row 3 | Cell in column 2, row 3

  |===
"""

----
When ::
I convert enriched docstring with asciidoc scenario tag using cukedoctor converter icon:thumbs-up[role="green",title="Passed"]
Then ::
DocString asciidoc output must be rendered in my documentation icon:thumbs-up[role="green",title="Passed"]
******

[discrete]
== *Features*
[discrete]
[discrete]
[[Discrete-class-feature, Discrete class feature]]
[discrete]
=== *Discrete class feature*
[discrete]
[discrete]
==== Scenario: Render source code
[discrete]
============
[discrete]
Given ::
[discrete]
the following source code in docstrings icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
[discrete]
*******
[discrete]
[discrete]
[discrete]
[discrete]
[source, java]
-----
public int sum(int x, int y){
    int result = x + y;
    return result; (1)
}
-----
[discrete]
[discrete]
[discrete]
<1> We can have callouts in living documentation
[discrete]
[discrete]
[discrete]
*******
============
[discrete]
[discrete]
==== Scenario: Render table
[discrete]
============
[discrete]
Given ::
[discrete]
the following table icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
[discrete]
*******
[discrete]
[discrete]
[discrete]
[discrete]
|===
| Cell in column 1, row 1 | Cell in column 2, row 1
| Cell in column 1, row 2 | Cell in column 2, row 2
| Cell in column 1, row 3 | Cell in column 2, row 3
|===
[discrete]
[discrete]
[discrete]
*******
============


******
==========

==== Whitespace in descriptions
Features and Scenarios can have multi-line descriptions. In a feature file, these may be indented.
Cukedoctor uses the indentation of the first line non-blank line of the description to determine the difference
between the indentation _of_ the description in a feature file and your desired indentation _within_ the the
description itself.

==========
Given ::
the feature: icon:thumbs-up[role="green",title="Passed"]
----

  Feature: Feature One


    This is the description for Feature One. The first non-blank line of this description in the feature file began with four whitespace characters.
      Therefore, cukedoctor will ignore up to the first four
whitespace characters
  in all other lines in the same description,
    if any are present.


This includes
  further lines
    in a different
      paragraph
        in the same description.



    Scenario: Scenario One

    This is the description for Scenario One. The first non-blank line of this description in the feature file began with four whitespace characters.
      Therefore, cukedoctor will ignore up to the first four
whitespace characters
  in all other lines in the same description,
    if any are present.


This includes
  further lines
    in a different
      paragraph
        in the same description.



    Scenario: Scenario Two
This scenario has no indentation. You don't have to use it, after all.
      Indentation in subsequent lines is therefore fully preserved.


----
When ::
I convert it icon:thumbs-up[role="green",title="Passed"]
Then ::
it should be rendered in AsciiDoc as icon:thumbs-up[role="green",title="Passed"]
******

[discrete]
== *Features*
[discrete]
[discrete]
[[Feature-One, Feature One]]
[discrete]
=== *Feature One*
[discrete]
[discrete]
*****
[discrete]
This is the description for Feature One. The first non-blank line of this description in the feature file began with four whitespace characters.
[discrete]
  Therefore, cukedoctor will ignore up to the first four
[discrete]
whitespace characters
[discrete]
in all other lines in the same description,
[discrete]
if any are present.
[discrete]
[discrete]
[discrete]
This includes
[discrete]
further lines
[discrete]
in a different
[discrete]
  paragraph
[discrete]
    in the same description.
[discrete]
*****
[discrete]
[discrete]
==== Scenario: Scenario One
[discrete]
This is the description for Scenario One. The first non-blank line of this description in the feature file began with four whitespace characters.
[discrete]
  Therefore, cukedoctor will ignore up to the first four
[discrete]
whitespace characters
[discrete]
in all other lines in the same description,
[discrete]
if any are present.
[discrete]
[discrete]
[discrete]
This includes
[discrete]
further lines
[discrete]
in a different
[discrete]
  paragraph
[discrete]
    in the same description.
[discrete]
[discrete]
==== Scenario: Scenario Two
[discrete]
This scenario has no indentation. You don't have to use it, after all.
[discrete]
      Indentation in subsequent lines is therefore fully preserved.


******
==========

[[Documentation-introduction-chapter, Documentation introduction chapter]]
=== *Documentation introduction chapter*

****
====
[quote]
____
In order to have an introduction chapter in my documentation
As a bdd developer
I want to be able to provide an asciidoc based document which introduces my software.
____
====
****

==== Introduction chapter in classpath
NOTE: The introduction file must be named *intro-chapter.adoc* and can be in any package of your application,

[TIP]
====
By default Cukedoctor will look into application folders but you can make Cukedoctor look into external folder by setting the following system property:
[source,java]
----
System.setProperty("INTRO_CHAPTER_DIR","/home/some/external/folder");
----
====

==========
Given ::
The following two features: icon:thumbs-up[role="green",title="Passed"]
----

Feature: Feature1

  Scenario: Scenario feature 1

    Given scenario step

Feature: Feature2

  Scenario: Scenario feature 2

    Given scenario step

----
And ::
The following asciidoc document is on your application classpath icon:thumbs-up[role="green",title="Passed"]
******

[discrete]
= *Introduction*
[discrete]
[discrete]
Cukedoctor is a *Living documentation* tool which integrates Cucumber and Asciidoctor in order to convert your _BDD_ tests results into an awesome documentation.
[discrete]
[discrete]
Here are some design principles:
[discrete]
[discrete]
* Living documentation should be readable and highlight your software features;
[discrete]
** Most bdd tools generate reports and not a truly documentation.
[discrete]
* Cukedoctor *do not* introduce a new API that you need to learn, instead it operates on top of http://www.relishapp.com/cucumber/cucumber/docs/formatters/json-output-formatter[cucumber json output^] files;
[discrete]
** In the 'worst case' to <<Enrich-features,enhance>> your documentation you will need to know a bit of http://asciidoctor.org/docs/what-is-asciidoc/[asciidoc markup^].


******
When ::
Bdd tests results are converted into documentation by Cukedoctor icon:thumbs-up[role="green",title="Passed"]
Then ::
Resulting documentation should have the provided introduction chapter icon:thumbs-up[role="green",title="Passed"]
******

[discrete]
[discrete]
= *Documentation*
[discrete]
[discrete]
== *Introduction*
[discrete]
[discrete]
Cukedoctor is a *Living documentation* tool which integrates Cucumber and Asciidoctor in order to convert your _BDD_ tests results into an awesome documentation.
[discrete]
[discrete]
Here are some design principles:
[discrete]
[discrete]
* Living documentation should be readable and highlight your software features;
[discrete]
** Most bdd tools generate reports and not a truly documentation.
[discrete]
* Cukedoctor *do not* introduce a new API that you need to learn, instead it operates on top of http://www.relishapp.com/cucumber/cucumber/docs/formatters/json-output-formatter[cucumber json output^] files;
[discrete]
** In the 'worst case' to <<Enrich-features,enhance>> your documentation you will need to know a bit of http://asciidoctor.org/docs/what-is-asciidoc/[asciidoc markup^].
[discrete]
[discrete]
== *Summary*
[discrete]
[cols="12*^m", options="header,footer"]
[discrete]
|===
3+|Scenarios 7+|Steps 2+|Features: 2
|[green]#*Passed*#
|[red]#*Failed*#
|Total
|[green]#*Passed*#
|[red]#*Failed*#
|[purple]#*Skipped*#
|[maroon]#*Pending*#
|[yellow]#*Undefined*#
|[blue]#*Missing*#
|Total
|Duration
|Status
12+^|*<<Feature1>>*
|1
|0
|1
|1
|0
|0
|0
|0
|0
|1
|647ms
|[green]#*passed*#
12+^|*<<Feature2>>*
|1
|0
|1
|1
|0
|0
|0
|0
|0
|1
|000ms
|[green]#*passed*#
12+^|*Totals*
|2|0|2|2|0|0|0|0|0|2 2+|647ms
|===
[discrete]
[discrete]
== *Features*
[discrete]
[discrete]
[[Feature1, Feature1]]
[discrete]
=== *Feature1*
[discrete]
[discrete]
==== Scenario: Scenario feature 1
[discrete]
============
[discrete]
Given ::
[discrete]
scenario step icon:thumbs-up[role="green",title="Passed"] [small right]#(647ms)#
============
[discrete]
[discrete]
[[Feature2, Feature2]]
[discrete]
=== *Feature2*
[discrete]
[discrete]
==== Scenario: Scenario feature 2
[discrete]
============
[discrete]
Given ::
[discrete]
scenario step icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
============


******
==========

[[Tag-rendering, Tag rendering]]
=== *Tag rendering*

==== Render feature tags in that feature's scenarios

==========
Given ::
The following two features: icon:thumbs-up[role="green",title="Passed"]
----

@someTag
Feature: Feature1

  @otherTag
  Scenario: Scenario feature 1

    Given scenario step

  @someTag @otherTag
  Scenario: Scenario feature 2

    Given scenario step

----
When ::
I render the feature icon:thumbs-up[role="green",title="Passed"]
Then ::
the tags displayed under each scenario should not have duplicates icon:thumbs-up[role="green",title="Passed"]
******

[discrete]
== *Features*
[discrete]
[discrete]
[[Feature1, Feature1]]
[discrete]
=== *Feature1*
[discrete]
[discrete]
==== Scenario: Scenario feature 1
[discrete]
[small]#tags: @someTag,@otherTag#
[discrete]
[discrete]
============
[discrete]
Given ::
[discrete]
scenario step icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
============
[discrete]
[discrete]
==== Scenario: Scenario feature 2
[discrete]
[small]#tags: @someTag,@otherTag#
[discrete]
[discrete]
============
[discrete]
Given ::
[discrete]
scenario step icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
============


******
==========

==== Ignore cukedoctor tags in resulting documentation
Cukedoctor specific tags like `@asciidoc` and `@order` *should not* be rendered in resulting documentation.

==========
Given ::
The following two features: icon:thumbs-up[role="green",title="Passed"]
----

@someTag @asciidoc @order-99
Feature: Feature1

  @otherTag @asciidoc
  Scenario: Scenario feature 1

    Given scenario step

  @someTag @otherTag
  Scenario: Scenario feature 2

    Given scenario step

----
When ::
I render the feature icon:thumbs-up[role="green",title="Passed"]
Then ::
Cukedoctor tags should not be rendered in documentation icon:thumbs-up[role="green",title="Passed"]
******

[discrete]
== *Features*
[discrete]
[discrete]
[[Feature1, Feature1]]
[discrete]
=== *Feature1*
[discrete]
[discrete]
==== Scenario: Scenario feature 1
[discrete]
[small]#tags: @someTag,@otherTag#
[discrete]
[discrete]
============
[discrete]
Given ::
[discrete]
scenario step icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
============
[discrete]
[discrete]
==== Scenario: Scenario feature 2
[discrete]
[small]#tags: @someTag,@otherTag#
[discrete]
[discrete]
============
[discrete]
Given ::
[discrete]
scenario step icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
============


******
==========

[[Attachments, Attachments]]
=== *Attachments*

****
====
[quote]
____
In order to capture dynamically-generated content from my tests
As a bdd developer
I want to render attachments from my Cucumber tests in my living documentation
____
====
****

==== Logging a string in Cucumber-JVM 6.7.0

==========
Given ::
a Step has logged a string in Cucumber-JVM 6.7.0 icon:thumbs-up[role="green",title="Passed"]
And ::
I am hiding step timings icon:thumbs-up[role="green",title="Passed"]
And ::
all Cukedoctor extensions are disabled icon:thumbs-up[role="green",title="Passed"]
When ::
I convert the Feature icon:thumbs-up[role="green",title="Passed"]
Then ::
it will be rendered as icon:thumbs-up[role="green",title="Passed"]
******

[discrete]
= *Features*
[discrete]
[discrete]
[discrete]
[[Attachments, Attachments]]
[discrete]
== *Attachments*
[discrete]
[discrete]
=== Scenario: Cucumber JVM 6.7.0 scenario.log(String)
[discrete]
============
[discrete]
Given ::
[discrete]
a Step that performs scenario.log(String) icon:thumbs-up[role="green",title="Passed"]
----
She sells sea shells on the sea shore
----
============


******
==========

==== Attaching plain text as a string with name in Cucumber-JVM 6.7.0

==========
Given ::
a Step has attached plain text as a string with a title in Cucumber-JVM 6.7.0 icon:thumbs-up[role="green",title="Passed"]
And ::
I am hiding step timings icon:thumbs-up[role="green",title="Passed"]
And ::
all Cukedoctor extensions are disabled icon:thumbs-up[role="green",title="Passed"]
When ::
I convert the Feature icon:thumbs-up[role="green",title="Passed"]
Then ::
it will be rendered as icon:thumbs-up[role="green",title="Passed"]
******

[discrete]
= *Features*
[discrete]
[discrete]
[discrete]
[[Attachments, Attachments]]
[discrete]
== *Attachments*
[discrete]
[discrete]
=== Scenario: Cucumber JVM 6.7.0 scenario.attach(String, String, String)
[discrete]
============
[discrete]
Given ::
[discrete]
a Step that performs scenario.attach(String, String, String) icon:thumbs-up[role="green",title="Passed"]
[discrete]
[discrete]
.String plain text
[discrete]
[%collapsible]
======
[discrete]
She sells sea shells on the sea shore
======
============


******
==========

==== Attaching plain text as a byte array with name in Cucumber-JVM 6.7.0

==========
Given ::
a Step has attached plain text as a byte array with a title in Cucumber-JVM 6.7.0 icon:thumbs-up[role="green",title="Passed"]
And ::
I am hiding step timings icon:thumbs-up[role="green",title="Passed"]
And ::
all Cukedoctor extensions are disabled icon:thumbs-up[role="green",title="Passed"]
When ::
I convert the Feature icon:thumbs-up[role="green",title="Passed"]
Then ::
it will be rendered as icon:thumbs-up[role="green",title="Passed"]
******

[discrete]
= *Features*
[discrete]
[discrete]
[discrete]
[[Attachments, Attachments]]
[discrete]
== *Attachments*
[discrete]
[discrete]
=== Scenario: Cucumber JVM 6.7.0 scenario.attach(ByteArray, String, String)
[discrete]
============
[discrete]
Given ::
[discrete]
a Step that performs scenario.attach(ByteArray, String, String) icon:thumbs-up[role="green",title="Passed"]
[discrete]
[discrete]
.Byte[] plain text
[discrete]
[%collapsible]
======
[discrete]
She sells sea shells on the sea shore
======
============


******
==========

==== Attaching a string CucumberJS 6.0.5

==========
Given ::
a Step has attached a string in CucumberJS 6.0.5 icon:thumbs-up[role="green",title="Passed"]
And ::
I am hiding step timings icon:thumbs-up[role="green",title="Passed"]
And ::
all Cukedoctor extensions are disabled icon:thumbs-up[role="green",title="Passed"]
When ::
I convert the Feature icon:thumbs-up[role="green",title="Passed"]
Then ::
it will be rendered as icon:thumbs-up[role="green",title="Passed"]
******

[discrete]
= *Features*
[discrete]
[discrete]
[discrete]
[[Attachments, Attachments]]
[discrete]
== *Attachments*
[discrete]
[discrete]
=== Scenario: Cucumber JS 6.0.5 attach String
[discrete]
============
[discrete]
Given ::
[discrete]
a Step that performs attach String icon:thumbs-up[role="green",title="Passed"]
[discrete]
[discrete]
.Attachment 1
[discrete]
[%collapsible]
======
[discrete]
She sells sea shells on the sea shore
======
============


******
==========

==== Attaching a plain text string CucumberJS 6.0.5

==========
Given ::
a Step has attached plain text as a string in CucumberJS 6.0.5 icon:thumbs-up[role="green",title="Passed"]
And ::
I am hiding step timings icon:thumbs-up[role="green",title="Passed"]
And ::
all Cukedoctor extensions are disabled icon:thumbs-up[role="green",title="Passed"]
When ::
I convert the Feature icon:thumbs-up[role="green",title="Passed"]
Then ::
it will be rendered as icon:thumbs-up[role="green",title="Passed"]
******

[discrete]
= *Features*
[discrete]
[discrete]
[discrete]
[[Attachments, Attachments]]
[discrete]
== *Attachments*
[discrete]
[discrete]
=== Scenario: Cucumber JS 6.0.5 attach String, String
[discrete]
============
[discrete]
Given ::
[discrete]
a Step that performs attach String, String icon:thumbs-up[role="green",title="Passed"]
[discrete]
[discrete]
.Attachment 1
[discrete]
[%collapsible]
======
[discrete]
She sells sea shells on the sea shore
======
============


******
==========

==== Attaching a plain text buffer CucumberJS 6.0.5

==========
Given ::
a Step has attached plain text as a buffer in CucumberJS 6.0.5 icon:thumbs-up[role="green",title="Passed"]
And ::
I am hiding step timings icon:thumbs-up[role="green",title="Passed"]
And ::
all Cukedoctor extensions are disabled icon:thumbs-up[role="green",title="Passed"]
When ::
I convert the Feature icon:thumbs-up[role="green",title="Passed"]
Then ::
it will be rendered as icon:thumbs-up[role="green",title="Passed"]
******

[discrete]
= *Features*
[discrete]
[discrete]
[discrete]
[[Attachments, Attachments]]
[discrete]
== *Attachments*
[discrete]
[discrete]
=== Scenario: Cucumber JS 6.0.5 attach Buffer, String
[discrete]
============
[discrete]
Given ::
[discrete]
a Step that performs attach Buffer, String icon:thumbs-up[role="green",title="Passed"]
[discrete]
[discrete]
.Attachment 1
[discrete]
[%collapsible]
======
[discrete]
She sells sea shells on the sea shore
======
============


******
==========

==== Logged text should appear before attachments

==========
Given ::
a Step has logged a string and attached a plain text string with a title icon:thumbs-up[role="green",title="Passed"]
And ::
I am hiding step timings icon:thumbs-up[role="green",title="Passed"]
And ::
all Cukedoctor extensions are disabled icon:thumbs-up[role="green",title="Passed"]
When ::
I convert the Feature icon:thumbs-up[role="green",title="Passed"]
Then ::
it will be rendered as icon:thumbs-up[role="green",title="Passed"]
******

[discrete]
= *Features*
[discrete]
[discrete]
[discrete]
[[Attachments, Attachments]]
[discrete]
== *Attachments*
[discrete]
[discrete]
=== Scenario: Log and attach
[discrete]
============
[discrete]
Given ::
[discrete]
a Step that logs and attaches icon:thumbs-up[role="green",title="Passed"]
----
Peter Piper picked a peck of pickled peppers
----
[discrete]
[discrete]
.String plain text
[discrete]
[%collapsible]
======
[discrete]
She sells sea shells on the sea shore
======
============


******
==========

==== Multiple attachments

==========
Given ::
a Step has three plain text attachments, two without a title icon:thumbs-up[role="green",title="Passed"]
And ::
I am hiding step timings icon:thumbs-up[role="green",title="Passed"]
And ::
all Cukedoctor extensions are disabled icon:thumbs-up[role="green",title="Passed"]
When ::
I convert the Feature icon:thumbs-up[role="green",title="Passed"]
Then ::
it will be rendered as icon:thumbs-up[role="green",title="Passed"]
******

[discrete]
= *Features*
[discrete]
[discrete]
[discrete]
[[Attachments, Attachments]]
[discrete]
== *Attachments*
[discrete]
[discrete]
=== Scenario: Multiple attachments
[discrete]
============
[discrete]
Given ::
[discrete]
a Step that has multiple attachments icon:thumbs-up[role="green",title="Passed"]
[discrete]
[discrete]
.Attachment 1
[discrete]
[%collapsible]
======
[discrete]
First attachment
======
[discrete]
[discrete]
.Second
[discrete]
[%collapsible]
======
[discrete]
Second Attachment
======
[discrete]
[discrete]
.Attachment 2
[discrete]
[%collapsible]
======
[discrete]
Third attachment
======
============


******
==========

==== Do not render attachments that are not plain text

==========
Given ::
a Step has logged an image/png attachment icon:thumbs-up[role="green",title="Passed"]
And ::
I am hiding step timings icon:thumbs-up[role="green",title="Passed"]
And ::
all Cukedoctor extensions are disabled icon:thumbs-up[role="green",title="Passed"]
When ::
I convert the Feature icon:thumbs-up[role="green",title="Passed"]
Then ::
it will be rendered as icon:thumbs-up[role="green",title="Passed"]
******

[discrete]
= *Features*
[discrete]
[discrete]
[discrete]
[[Attachments, Attachments]]
[discrete]
== *Attachments*
[discrete]
[discrete]
=== Scenario: Attaching an image
[discrete]
============
[discrete]
Given ::
[discrete]
a Step that attaches an image icon:thumbs-up[role="green",title="Passed"]
============


******
==========

