:toc: center
:backend: pdf
:doctitle: Cukedoctor Documentation
:doctype: book
:icons: font
:numbered:
:!linkcss:
:sectanchors:
:sectlink:
:docinfo:
:source-highlighter: highlightjs
:toclevels: 3
:revnumber: 1.1.0
:hardbreaks:

= *Cukedoctor Documentation*

include::/home/travis/build/rmpestano/cukedoctor/cukedoctor-converter/target/test-classes/cukedoctor-intro.adoc[leveloffset=+1]


== *Features*

[[Cukedoctor-Converter, Cukedoctor Converter]]
=== *Cukedoctor Converter*

****
====
[quote]
____
In order to have awesome _living documentation_
As a bdd developer
I want to use *Cukedoctor* to convert my cucumber test results into `readable` living documentation.
____
====
****

==== Convert features test output into documentation

****
Given ::
=====
The following two features: icon:thumbs-up[role="green",title="Passed"] [small right]#(336ms)#
----

Feature: Feature1

  Scenario: Scenario feature 1

    Given scenario step

Feature: Feature2

  Scenario: Scenario feature 2

    Given scenario step

----
=====
When ::
=====
I convert their json test output using cukedoctor converter icon:thumbs-up[role="green",title="Passed"] [small right]#(915ms)#
******

[discrete]
[IMPORTANT]
=======
[discrete]
To generate cucumber .json output files just execute your _BDD_ tests with *json* formatter, example:
[discrete]
[discrete]
[source,java]
----
@RunWith(Cucumber.class)
@CucumberOptions(plugin = {"json:target/cucumber.json"} )
----
[discrete]
NOTE: *plugin* option replaced *format* option which was deprecated in newer cucumber versions.
[discrete]
=======


******

=====
Then ::
=====
I should have awesome living documentation icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
******

[discrete]
[discrete]
= *Documentation*
[discrete]
[discrete]
[discrete]
[discrete]
== *Summary*
[discrete]
[cols="12*^m", options="header,footer"]
[discrete]
|===
3+|Scenarios 7+|Steps 2+|Features: 2
|[green]#*Passed*#
|[red]#*Failed*#
|Total
|[green]#*Passed*#
|[red]#*Failed*#
|[purple]#*Skipped*#
|[maroon]#*Pending*#
|[yellow]#*Undefined*#
|[blue]#*Missing*#
|Total
|Duration
|Status
12+^|*<<Feature1>>*
|1
|0
|1
|1
|0
|0
|0
|0
|0
|1
|647ms
|[green]#*passed*#
12+^|*<<Feature2>>*
|1
|0
|1
|1
|0
|0
|0
|0
|0
|1
|000ms
|[green]#*passed*#
12+^|*Totals*
|2|0|2|2|0|0|0|0|0|2 2+|647ms
|===
[discrete]
[discrete]
== *Features*
[discrete]
[discrete]
[[Feature1, Feature1]]
[discrete]
=== *Feature1*
[discrete]
[discrete]
==== Scenario: Scenario feature 1
[discrete]
[discrete]
*****
[discrete]
Given ::
======
[discrete]
scenario step icon:thumbs-up[role="green",title="Passed"] [small right]#(647ms)#
======
[discrete]
*****
[discrete]
[discrete]
[[Feature2, Feature2]]
[discrete]
=== *Feature2*
[discrete]
[discrete]
==== Scenario: Scenario feature 2
[discrete]
[discrete]
*****
[discrete]
Given ::
======
[discrete]
scenario step icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
======
[discrete]
*****


******

=====
****

[[Ordering, Ordering]]
=== *Ordering*

****
====
[quote]
____
In order to have features ordered in living documentation
As a bdd developer
I want to control the order of features in my documentation
____
====
****

==== Default ordering

****
Given ::
=====
The following two features: icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

Feature: Feature1

  Scenario: Scenario feature 1

    Given scenario step

Feature: Feature2

  Scenario: Scenario feature 2

    Given scenario step

----
=====
When ::
=====
I convert them using default order icon:thumbs-up[role="green",title="Passed"] [small right]#(033ms)#
=====
Then ::
=====
Features should be ordered by name in resulting documentation icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
******

[discrete]
[[Feature1, Feature1]]
[discrete]
=== *Feature1*
[discrete]
[discrete]
==== Scenario: Scenario feature 1
[discrete]
[discrete]
*****
[discrete]
Given ::
======
[discrete]
scenario step icon:thumbs-up[role="green",title="Passed"] [small right]#(647ms)#
======
[discrete]
*****
[discrete]
[discrete]
[[Feature2, Feature2]]
[discrete]
=== *Feature2*
[discrete]
[discrete]
==== Scenario: Scenario feature 2
[discrete]
[discrete]
*****
[discrete]
Given ::
======
[discrete]
scenario step icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
======
[discrete]
*****


******

=====
****

==== Custom ordering

****
Given ::
=====
The following two features: icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

#order: 2
Feature: Feature1

  Scenario: Scenario feature 1

    Given scenario step

#order: 1
Feature: Feature2

  Scenario: Scenario feature 2

    Given scenario step

----

NOTE: Ordering is done using feature comment '*#order:*'

=====
When ::
=====
I convert them using comment order icon:thumbs-up[role="green",title="Passed"] [small right]#(032ms)#
=====
Then ::
=====
Features should be ordered respecting order comment icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
******

[discrete]
[[Feature2, Feature2]]
[discrete]
=== *Feature2*
[discrete]
[discrete]
==== Scenario: Scenario feature 2
[discrete]
[discrete]
*****
[discrete]
Given ::
======
[discrete]
scenario step icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
======
[discrete]
*****
[discrete]
[discrete]
[[Feature1, Feature1]]
[discrete]
=== *Feature1*
[discrete]
[discrete]
==== Scenario: Scenario feature 1
[discrete]
[discrete]
*****
[discrete]
Given ::
======
[discrete]
scenario step icon:thumbs-up[role="green",title="Passed"] [small right]#(313ms)#
======
[discrete]
*****


******

=====
****

[[Enrich-features, Enrich features]]
=== *Enrich features*

****
====
[quote]
____
In order to have awesome _living documentation_
As a bdd developer
I want to render asciidoc markup inside my features.
____
====
****

==== DocSting enrichment
Asciidoc markup can be used in feature *DocStrings*. To do so you need to enable it by using *[cukector-dicrete]* comment on the feature.

****
Given ::
=====
The following two features: icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

Feature: Enrich feature

  Scenario: Render source code

    # cukedoctor-discrete
    Given the following source code in docstrings
"""
  [source, java]
  -----
  public int sum(int x, int y){
  int result = x + y;
  return result; (1)
  }
  -----
  <1> We can have callouts in living documentation
"""

  Scenario: Render table

    # cukedoctor-discrete
    Given the following table
 """
  |===

  | Cell in column 1, row 1 | Cell in column 2, row 1
  | Cell in column 1, row 2 | Cell in column 2, row 2
  | Cell in column 1, row 3 | Cell in column 2, row 3

  |===
"""

----
=====
When ::
=====
I convert docstring enriched json output using cukedoctor converter icon:thumbs-up[role="green",title="Passed"] [small right]#(060ms)#
=====
Then ::
=====
DocString asciidoc output must be rendered in my documentation icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
******

[discrete]
[[Discrete-class-feature, Discrete class feature]]
[discrete]
=== *Discrete class feature*
[discrete]
[discrete]
==== Scenario: Render source code
[discrete]
[discrete]
*****
[discrete]
Given ::
======
[discrete]
the following source code icon:thumbs-up[role="green",title="Passed"] [small right]#(267ms)#
[discrete]
*******
[discrete]
[discrete]
[discrete]
[discrete]
[source, java]
-----
public int sum(int x, int y){
    int result = x + y;
    return result; <1>
}
-----
<1> We can have callouts in living documentation>
[discrete]
[discrete]
[discrete]
*******
[discrete]
======
[discrete]
*****
[discrete]
[discrete]
==== Scenario: Render table
[discrete]
[discrete]
*****
[discrete]
Given ::
======
[discrete]
the following table icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
[discrete]
*******
[discrete]
[discrete]
[discrete]
[discrete]
|===
| Cell in column 1, row 1 | Cell in column 2, row 1
| Cell in column 1, row 2 | Cell in column 2, row 2
| Cell in column 1, row 3 | Cell in column 2, row 3
|===
[discrete]
[discrete]
[discrete]
*******
[discrete]
======
[discrete]
*****


******

=====
****

==== Comments enrichment
Asciidoc markup can be used in feature comments. To do so you need to surround asciidoc markup by *curly brackets*;.

****
Given ::
=====
The following feature with asciidoc markup in comments: icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

Feature: Calculator

  Scenario: Adding numbers
   You can *asciidoc markup* in _feature_ #description#.

    NOTE: This is a very important feature!

    #{IMPORTANT: Asciidoc markup inside *steps* must be surrounded by *curly brackets*.}
    Given I have numbers 1 and 2

    # {NOTE: Steps comments are placed *before* each steps so this comment is for the *WHEN* step.}

    When I sum the numbers
    # {* this is a list of itens inside a feature step}
    # {* there is no multiline comment in gherkin}
    # {** second level list item}
    Then I should have 3 as result


----
=====
When ::
=====
I convert enriched feature json output using cukedoctor icon:thumbs-up[role="green",title="Passed"] [small right]#(036ms)#
=====
Then ::
=====
Asciidoc markup on comments must be rendered in my documentation icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
******

[discrete]
[[Calculator, Calculator]]
[discrete]
=== *Calculator*
[discrete]
[discrete]
==== Scenario: Adding numbers
[discrete]
You can use *asciidoc markup* in _feature_ #description#.
[discrete]
[discrete]
NOTE: This is a very important feature!
[discrete]
[discrete]
*****
[discrete]
Given ::
======
[discrete]
I have numbers 1 and 2 icon:thumbs-up[role="green",title="Passed"] [small right]#(114ms)#
[discrete]
[discrete]
IMPORTANT: Asciidoc markup inside *steps* must be surrounded by *curly brackets*.
[discrete]
======
[discrete]
When ::
======
[discrete]
I sum the numbers icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
[discrete]
[discrete]
NOTE: Steps comments are placed *before* each steps so this comment is for the *WHEN* step.
[discrete]
======
[discrete]
Then ::
======
[discrete]
I should have 3 as result icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
[discrete]
[discrete]
* this is a list of itens inside a feature step
[discrete]
[discrete]
* there is no multiline comment in gherkin
[discrete]
[discrete]
** second level list item
[discrete]
======
[discrete]
*****


******

=====
****

[[Documentation-introduction-chapter, Documentation introduction chapter]]
=== *Documentation introduction chapter*

****
====
[quote]
____
In order to have an introduction chapter in my documentation
As a bdd developer
I want to be able to provide an asciidoc based document which introduces my software.
____
====
****

==== Introduction chapter in classpath

****
Given ::
=====
The following two features: icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

Feature: Feature1

  Scenario: Scenario feature 1

    Given scenario step

Feature: Feature2

  Scenario: Scenario feature 2

    Given scenario step

----
=====
And ::
=====
The following asciidoc document is on your application classpath icon:thumbs-up[role="green",title="Passed"] [small right]#(042ms)#
******

[discrete]
= *Introduction*
[discrete]
[discrete]
Cukedoctor is a *Living documentation* tool which integrates Cucumber and Asciidoctor in order to convert your _BDD_ tests results into an awesome documentation.
[discrete]
[discrete]
Here are some design principles:
[discrete]
[discrete]
* Living documentation should be readable and highlight your software features;
[discrete]
** Most bdd tools generate reports and not a truly documentation.
[discrete]
* Cukedoctor *do not* introduce a new API that you need to learn, instead it operates on top of http://www.relishapp.com/cucumber/cucumber/docs/formatters/json-output-formatter[cucumber json output^] files;
[discrete]
** In the 'worst case' to <<Enrich-features,enhance>> your documentation you will need to know a bit of http://asciidoctor.org/docs/what-is-asciidoc/[asciidoc markup^].


******

NOTE: The introduction file must be named *intro-chapter.adoc* and can be in any package of your application,

[TIP]
====

By default Cukedoctor will look into application folders but you can make Cukedoctor look into external folder by setting the following system property:
[source,java]
----

System.setProperty("INTRO_CHAPTER_DIR","/home/some/external/folder");
----
====

=====
When ::
=====
Bdd tests results are converted into documentation by Cukedoctor icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
=====
Then ::
=====
Resulting documentation should have the provided introduction chapter icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
******

[discrete]
[discrete]
= *Documentation*
[discrete]
[discrete]
== *Introduction*
[discrete]
[discrete]
Cukedoctor is a *Living documentation* tool which integrates Cucumber and Asciidoctor in order to convert your _BDD_ tests results into an awesome documentation.
[discrete]
[discrete]
Here are some design principles:
[discrete]
[discrete]
* Living documentation should be readable and highlight your software features;
[discrete]
** Most bdd tools generate reports and not a truly documentation.
[discrete]
* Cukedoctor *do not* introduce a new API that you need to learn, instead it operates on top of http://www.relishapp.com/cucumber/cucumber/docs/formatters/json-output-formatter[cucumber json output^] files;
[discrete]
** In the 'worst case' to <<Enrich-features,enhance>> your documentation you will need to know a bit of http://asciidoctor.org/docs/what-is-asciidoc/[asciidoc markup^].
[discrete]
[discrete]
== *Summary*
[discrete]
[cols="12*^m", options="header,footer"]
[discrete]
|===
3+|Scenarios 7+|Steps 2+|Features: 2
|[green]#*Passed*#
|[red]#*Failed*#
|Total
|[green]#*Passed*#
|[red]#*Failed*#
|[purple]#*Skipped*#
|[maroon]#*Pending*#
|[yellow]#*Undefined*#
|[blue]#*Missing*#
|Total
|Duration
|Status
12+^|*<<Feature1>>*
|1
|0
|1
|1
|0
|0
|0
|0
|0
|1
|647ms
|[green]#*passed*#
12+^|*<<Feature2>>*
|1
|0
|1
|1
|0
|0
|0
|0
|0
|1
|000ms
|[green]#*passed*#
12+^|*Totals*
|2|0|2|2|0|0|0|0|0|2 2+|647ms
|===
[discrete]
[discrete]
== *Features*
[discrete]
[discrete]
[[Feature1, Feature1]]
[discrete]
=== *Feature1*
[discrete]
[discrete]
==== Scenario: Scenario feature 1
[discrete]
[discrete]
*****
[discrete]
Given ::
======
[discrete]
scenario step icon:thumbs-up[role="green",title="Passed"] [small right]#(647ms)#
======
[discrete]
*****
[discrete]
[discrete]
[[Feature2, Feature2]]
[discrete]
=== *Feature2*
[discrete]
[discrete]
==== Scenario: Scenario feature 2
[discrete]
[discrete]
*****
[discrete]
Given ::
======
[discrete]
scenario step icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
======
[discrete]
*****


******

=====
****

