:toc: center
:backend: pdf
:doctitle: Cukedoctor Documentation
:doctype: book
:icons: font
:numbered:
:!linkcss:
:sectanchors:
:sectlink:
:docinfo:
:source-highlighter: highlightjs
:toclevels: 3
:revnumber: 2.1-SNAPSHOT
:hardbreaks:
:chapter-label: Chapter
:version-label: Version

= *Cukedoctor Documentation*

include::/home/travis/build/rmpestano/cukedoctor/cukedoctor-converter/target/test-classes/cukedoctor-intro.adoc[leveloffset=+1]


== *Features*

[[Cukedoctor-Converter, Cukedoctor Converter]]
=== *Cukedoctor Converter*

****
====
[quote]
____
In order to have awesome _living documentation_
As a bdd developer
I want to use *Cukedoctor* to convert my cucumber test results into `readable` living documentation.
____
====
****

==== Convert features test output into documentation

==========
Given ::
The following two features: icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

Feature: Feature1

  Scenario: Scenario feature 1

    Given scenario step

Feature: Feature2

  Scenario: Scenario feature 2

    Given scenario step

----
When ::
I convert their json test output using cukedoctor converter icon:thumbs-up[role="green",title="Passed"] [small right]#(009ms)#
******

[discrete]
[IMPORTANT]
=======
[discrete]
To generate cucumber .json output files just execute your _BDD_ tests with *json* formatter, example:
[discrete]
[discrete]
[source,java]
----
@RunWith(Cucumber.class)
@CucumberOptions(plugin = {"json:target/cucumber.json"} )
----
[discrete]
NOTE: *plugin* option replaced *format* option which was deprecated in newer cucumber versions.
[discrete]
=======


******
Then ::
I should have awesome living documentation icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
******

[discrete]
[discrete]
= *Documentation*
[discrete]
[discrete]
[discrete]
[discrete]
== *Summary*
[discrete]
[cols="12*^m", options="header,footer"]
[discrete]
|===
3+|Scenarios 7+|Steps 2+|Features: 2
|[green]#*Passed*#
|[red]#*Failed*#
|Total
|[green]#*Passed*#
|[red]#*Failed*#
|[purple]#*Skipped*#
|[maroon]#*Pending*#
|[yellow]#*Undefined*#
|[blue]#*Missing*#
|Total
|Duration
|Status
12+^|*<<Feature1>>*
|1
|0
|1
|1
|0
|0
|0
|0
|0
|1
|647ms
|[green]#*passed*#
12+^|*<<Feature2>>*
|1
|0
|1
|1
|0
|0
|0
|0
|0
|1
|000ms
|[green]#*passed*#
12+^|*Totals*
|2|0|2|2|0|0|0|0|0|2 2+|647ms
|===
[discrete]
[discrete]
== *Features*
[discrete]
[discrete]
[[Feature1, Feature1]]
[discrete]
=== *Feature1*
[discrete]
[discrete]
==== Scenario: Scenario feature 1
[discrete]
============
[discrete]
Given ::
[discrete]
scenario step icon:thumbs-up[role="green",title="Passed"] [small right]#(647ms)#
============
[discrete]
[discrete]
[[Feature2, Feature2]]
[discrete]
=== *Feature2*
[discrete]
[discrete]
==== Scenario: Scenario feature 2
[discrete]
============
[discrete]
Given ::
[discrete]
scenario step icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
============


******
==========

[[Ordering, Ordering]]
=== *Ordering*

****
====
[quote]
____
In order to have features ordered in living documentation
As a bdd developer
I want to control the order of features in my documentation
____
====
****

==== Default ordering

==========
Given ::
The following two features: icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

Feature: Feature1

  Scenario: Scenario feature 1

    Given scenario step

Feature: Feature2

  Scenario: Scenario feature 2

    Given scenario step

----
When ::
I convert them using default order icon:thumbs-up[role="green",title="Passed"] [small right]#(006ms)#
Then ::
Features should be ordered by name in resulting documentation icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
******

[discrete]
== *Features*
[discrete]
[discrete]
[[Feature1, Feature1]]
[discrete]
=== *Feature1*
[discrete]
[discrete]
==== Scenario: Scenario feature 1
[discrete]
============
[discrete]
Given ::
[discrete]
scenario step icon:thumbs-up[role="green",title="Passed"] [small right]#(647ms)#
============
[discrete]
[discrete]
[[Feature2, Feature2]]
[discrete]
=== *Feature2*
[discrete]
[discrete]
==== Scenario: Scenario feature 2
[discrete]
============
[discrete]
Given ::
[discrete]
scenario step icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
============


******
==========

==== Custom ordering with tags
NOTE: Ordering is done using feature tag *@order-*

==========
Given ::
The following two features: icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

@order-2
Feature: Feature1

  Scenario: Scenario feature 1

    Given scenario step

@order-1
Feature: Feature2

  Scenario: Scenario feature 2

    Given scenario step

----
When ::
I convert them using tag order icon:thumbs-up[role="green",title="Passed"] [small right]#(005ms)#
Then ::
Features should be ordered respecting order tag icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
******

[discrete]
== *Features*
[discrete]
[discrete]
[[Feature2, Feature2]]
[discrete]
=== *Feature2*
[discrete]
[discrete]
==== Scenario: Scenario feature 2
[discrete]
============
[discrete]
Given ::
[discrete]
scenario step icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
============
[discrete]
[discrete]
[[Feature1, Feature1]]
[discrete]
=== *Feature1*
[discrete]
[discrete]
==== Scenario: Scenario feature 1
[discrete]
============
[discrete]
Given ::
[discrete]
scenario step icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
============


******
==========

[[Enrich-features, Enrich features]]
=== *Enrich features*

****
====
[quote]
____
In order to have awesome _living documentation_
As a bdd developer
I want to render asciidoc markup inside my features.
____
====

https://asciidoctor.org/docs/what-is-asciidoc/[Asciidoc^] markup can be used in feature *DocStrings*. To do so you can enable it by using *@asciidoc* tag at `feature` or `scenario` level.

[IMPORTANT]
=====
Adding @asciidoc tag at *feature level* will make cukedoctor interpret `all features docstrings` as Asciidoc markup.

Adding @asciidoc at *scenario level* will make cukedoctor interpret `all steps docstrings` as asciidoc markup.

TIP: To enable asciidoc markup in a *single step* you can use `asciidoc` as https://relishapp.com/cucumber/cucumber/docs/gherkin/doc-strings#docstring-with-interesting-content-type[docstring content type^].
=====

NOTE: Feature and scenario descriptions are automatically interpreted as Asciidoc markup without the need for adding the feature tag.
****

==== DocString enrichment activated by the content type
Asciidoc markup can be used in feature *DocStrings*. To do so you can enable it by using the content type *[asciidoc]* in the DocString.

==========
Given ::
The following two features: icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

Feature: Discrete class feature

  Scenario: Render source code

    Given the following source code in docstrings
"""asciidoc
  [source, java]
  -----
  public int sum(int x, int y){
  int result = x + y;
  return result; (1)
  }
  -----
  <1> We can have callouts in living documentation
"""

  Scenario: Render table

    Given the following table
 """asciidoc
  |===

  | Cell in column 1, row 1 | Cell in column 2, row 1
  | Cell in column 1, row 2 | Cell in column 2, row 2
  | Cell in column 1, row 3 | Cell in column 2, row 3

  |===
"""

----
When ::
I convert enriched docstring with asciidoc content type using cukedoctor converter icon:thumbs-up[role="green",title="Passed"] [small right]#(006ms)#
Then ::
DocString asciidoc output must be rendered in my documentation icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
******

[discrete]
== *Features*
[discrete]
[discrete]
[[Discrete-class-feature, Discrete class feature]]
[discrete]
=== *Discrete class feature*
[discrete]
[discrete]
==== Scenario: Render source code
[discrete]
============
[discrete]
Given ::
[discrete]
the following source code in docstrings icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
[discrete]
*******
[discrete]
[discrete]
[discrete]
[discrete]
[source, java]
-----
public int sum(int x, int y){
    int result = x + y;
    return result; (1)
}
-----
[discrete]
[discrete]
[discrete]
<1> We can have callouts in living documentation
[discrete]
[discrete]
[discrete]
*******
============
[discrete]
[discrete]
==== Scenario: Render table
[discrete]
============
[discrete]
Given ::
[discrete]
the following table icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
[discrete]
*******
[discrete]
[discrete]
[discrete]
[discrete]
|===
| Cell in column 1, row 1 | Cell in column 2, row 1
| Cell in column 1, row 2 | Cell in column 2, row 2
| Cell in column 1, row 3 | Cell in column 2, row 3
|===
[discrete]
[discrete]
[discrete]
*******
============


******
==========

==== DocString enrichment activated by a feature tag
Asciidoc markup can be used in feature *DocStrings*. You can enable this by applying the tag [@asciidoc] to the feature. Note this enables the enrichment for all DocStrings within the feature.

==========
Given ::
The following two features: icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

@asciidoc
Feature: Discrete class feature

  Scenario: Render source code

    Given the following source code in docstrings
"""
  [source, java]
  -----
  public int sum(int x, int y){
  int result = x + y;
  return result; (1)
  }
  -----
  <1> We can have callouts in living documentation
"""

  Scenario: Render table

    Given the following table
 """
  |===

  | Cell in column 1, row 1 | Cell in column 2, row 1
  | Cell in column 1, row 2 | Cell in column 2, row 2
  | Cell in column 1, row 3 | Cell in column 2, row 3

  |===
"""

----
When ::
I convert enriched docstring with asciidoc feature tag using cukedoctor converter icon:thumbs-up[role="green",title="Passed"] [small right]#(007ms)#
Then ::
DocString asciidoc output must be rendered in my documentation icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
******

[discrete]
== *Features*
[discrete]
[discrete]
[[Discrete-class-feature, Discrete class feature]]
[discrete]
=== *Discrete class feature*
[discrete]
[discrete]
==== Scenario: Render source code
[discrete]
============
[discrete]
Given ::
[discrete]
the following source code in docstrings icon:thumbs-up[role="green",title="Passed"] [small right]#(011ms)#
[discrete]
*******
[discrete]
[discrete]
[discrete]
[discrete]
[source, java]
-----
public int sum(int x, int y){
    int result = x + y;
    return result; (1)
}
-----
[discrete]
[discrete]
[discrete]
<1> We can have callouts in living documentation
[discrete]
[discrete]
[discrete]
*******
============
[discrete]
[discrete]
==== Scenario: Render table
[discrete]
============
[discrete]
Given ::
[discrete]
the following table icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
[discrete]
*******
[discrete]
[discrete]
[discrete]
[discrete]
|===
| Cell in column 1, row 1 | Cell in column 2, row 1
| Cell in column 1, row 2 | Cell in column 2, row 2
| Cell in column 1, row 3 | Cell in column 2, row 3
|===
[discrete]
[discrete]
[discrete]
*******
============


******
==========

==== DocString enrichment activated by a scenario tag
Asciidoc markup can be used in feature *DocStrings*. You can enable this by applying the tag [@asciidoc] to the scenario. Note this enables the enrichment for all DocStrings within the scenario.

==========
Given ::
The following two features: icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

Feature: Discrete class feature

  @asciidoc
  Scenario: Render source code

    Given the following source code in docstrings
"""
  [source, java]
  -----
  public int sum(int x, int y){
  int result = x + y;
  return result; (1)
  }
  -----
  <1> We can have callouts in living documentation
"""

  @asciidoc
  Scenario: Render table

    Given the following table
 """
  |===

  | Cell in column 1, row 1 | Cell in column 2, row 1
  | Cell in column 1, row 2 | Cell in column 2, row 2
  | Cell in column 1, row 3 | Cell in column 2, row 3

  |===
"""

----
When ::
I convert enriched docstring with asciidoc scenario tag using cukedoctor converter icon:thumbs-up[role="green",title="Passed"] [small right]#(006ms)#
Then ::
DocString asciidoc output must be rendered in my documentation icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
******

[discrete]
== *Features*
[discrete]
[discrete]
[[Discrete-class-feature, Discrete class feature]]
[discrete]
=== *Discrete class feature*
[discrete]
[discrete]
==== Scenario: Render source code
[discrete]
============
[discrete]
Given ::
[discrete]
the following source code in docstrings icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
[discrete]
*******
[discrete]
[discrete]
[discrete]
[discrete]
[source, java]
-----
public int sum(int x, int y){
    int result = x + y;
    return result; (1)
}
-----
[discrete]
[discrete]
[discrete]
<1> We can have callouts in living documentation
[discrete]
[discrete]
[discrete]
*******
============
[discrete]
[discrete]
==== Scenario: Render table
[discrete]
============
[discrete]
Given ::
[discrete]
the following table icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
[discrete]
*******
[discrete]
[discrete]
[discrete]
[discrete]
|===
| Cell in column 1, row 1 | Cell in column 2, row 1
| Cell in column 1, row 2 | Cell in column 2, row 2
| Cell in column 1, row 3 | Cell in column 2, row 3
|===
[discrete]
[discrete]
[discrete]
*******
============


******
==========

[[Documentation-introduction-chapter, Documentation introduction chapter]]
=== *Documentation introduction chapter*

****
====
[quote]
____
In order to have an introduction chapter in my documentation
As a bdd developer
I want to be able to provide an asciidoc based document which introduces my software.
____
====
****

==== Introduction chapter in classpath
NOTE: The introduction file must be named *intro-chapter.adoc* and can be in any package of your application,

[TIP]
====
By default Cukedoctor will look into application folders but you can make Cukedoctor look into external folder by setting the following system property:
[source,java]
----
System.setProperty("INTRO_CHAPTER_DIR","/home/some/external/folder");
----
====

==========
Given ::
The following two features: icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

Feature: Feature1

  Scenario: Scenario feature 1

    Given scenario step

Feature: Feature2

  Scenario: Scenario feature 2

    Given scenario step

----
And ::
The following asciidoc document is on your application classpath icon:thumbs-up[role="green",title="Passed"] [small right]#(006ms)#
******

[discrete]
= *Introduction*
[discrete]
[discrete]
Cukedoctor is a *Living documentation* tool which integrates Cucumber and Asciidoctor in order to convert your _BDD_ tests results into an awesome documentation.
[discrete]
[discrete]
Here are some design principles:
[discrete]
[discrete]
* Living documentation should be readable and highlight your software features;
[discrete]
** Most bdd tools generate reports and not a truly documentation.
[discrete]
* Cukedoctor *do not* introduce a new API that you need to learn, instead it operates on top of http://www.relishapp.com/cucumber/cucumber/docs/formatters/json-output-formatter[cucumber json output^] files;
[discrete]
** In the 'worst case' to <<Enrich-features,enhance>> your documentation you will need to know a bit of http://asciidoctor.org/docs/what-is-asciidoc/[asciidoc markup^].


******
When ::
Bdd tests results are converted into documentation by Cukedoctor icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
Then ::
Resulting documentation should have the provided introduction chapter icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
******

[discrete]
[discrete]
= *Documentation*
[discrete]
[discrete]
== *Introduction*
[discrete]
[discrete]
Cukedoctor is a *Living documentation* tool which integrates Cucumber and Asciidoctor in order to convert your _BDD_ tests results into an awesome documentation.
[discrete]
[discrete]
Here are some design principles:
[discrete]
[discrete]
* Living documentation should be readable and highlight your software features;
[discrete]
** Most bdd tools generate reports and not a truly documentation.
[discrete]
* Cukedoctor *do not* introduce a new API that you need to learn, instead it operates on top of http://www.relishapp.com/cucumber/cucumber/docs/formatters/json-output-formatter[cucumber json output^] files;
[discrete]
** In the 'worst case' to <<Enrich-features,enhance>> your documentation you will need to know a bit of http://asciidoctor.org/docs/what-is-asciidoc/[asciidoc markup^].
[discrete]
[discrete]
== *Summary*
[discrete]
[cols="12*^m", options="header,footer"]
[discrete]
|===
3+|Scenarios 7+|Steps 2+|Features: 2
|[green]#*Passed*#
|[red]#*Failed*#
|Total
|[green]#*Passed*#
|[red]#*Failed*#
|[purple]#*Skipped*#
|[maroon]#*Pending*#
|[yellow]#*Undefined*#
|[blue]#*Missing*#
|Total
|Duration
|Status
12+^|*<<Feature1>>*
|1
|0
|1
|1
|0
|0
|0
|0
|0
|1
|647ms
|[green]#*passed*#
12+^|*<<Feature2>>*
|1
|0
|1
|1
|0
|0
|0
|0
|0
|1
|000ms
|[green]#*passed*#
12+^|*Totals*
|2|0|2|2|0|0|0|0|0|2 2+|647ms
|===
[discrete]
[discrete]
== *Features*
[discrete]
[discrete]
[[Feature1, Feature1]]
[discrete]
=== *Feature1*
[discrete]
[discrete]
==== Scenario: Scenario feature 1
[discrete]
============
[discrete]
Given ::
[discrete]
scenario step icon:thumbs-up[role="green",title="Passed"] [small right]#(647ms)#
============
[discrete]
[discrete]
[[Feature2, Feature2]]
[discrete]
=== *Feature2*
[discrete]
[discrete]
==== Scenario: Scenario feature 2
[discrete]
============
[discrete]
Given ::
[discrete]
scenario step icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
============


******
==========

[[Tag-rendering, Tag rendering]]
=== *Tag rendering*

==== Render feature tags in that feature's scenarios

==========
Given ::
The following two features: icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

@someTag
Feature: Feature1

  @otherTag
  Scenario: Scenario feature 1

    Given scenario step

  @someTag @otherTag
  Scenario: Scenario feature 2

    Given scenario step

----
When ::
I render the feature icon:thumbs-up[role="green",title="Passed"] [small right]#(006ms)#
Then ::
the tags displayed under each scenario should not have duplicates icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
******

[discrete]
== *Features*
[discrete]
[discrete]
[[Feature1, Feature1]]
[discrete]
=== *Feature1*
[discrete]
[discrete]
==== Scenario: Scenario feature 1
[discrete]
[small]#tags: @someTag,@otherTag#
[discrete]
[discrete]
============
[discrete]
Given ::
[discrete]
scenario step icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
============
[discrete]
[discrete]
==== Scenario: Scenario feature 2
[discrete]
[small]#tags: @someTag,@otherTag#
[discrete]
[discrete]
============
[discrete]
Given ::
[discrete]
scenario step icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
============


******
==========

==== Ignore cukedoctor tags in resulting documentation
Cukedoctor specific tags like `@asciidoc` and `@order` *should not* be rendered in resulting documentation.

==========
Given ::
The following two features: icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
----

@someTag @asciidoc @order-99
Feature: Feature1

  @otherTag @asciidoc
  Scenario: Scenario feature 1

    Given scenario step

  @someTag @otherTag
  Scenario: Scenario feature 2

    Given scenario step

----
When ::
I render the feature icon:thumbs-up[role="green",title="Passed"] [small right]#(005ms)#
Then ::
Cukedoctor tags should not be rendered in documentation icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
******

[discrete]
== *Features*
[discrete]
[discrete]
[[Feature1, Feature1]]
[discrete]
=== *Feature1*
[discrete]
[discrete]
==== Scenario: Scenario feature 1
[discrete]
[small]#tags: @someTag,@otherTag#
[discrete]
[discrete]
============
[discrete]
Given ::
[discrete]
scenario step icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
============
[discrete]
[discrete]
==== Scenario: Scenario feature 2
[discrete]
[small]#tags: @someTag,@otherTag#
[discrete]
[discrete]
============
[discrete]
Given ::
[discrete]
scenario step icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
============


******
==========

