layoutConfig:
  hideFeaturesSection: false
  hideSummarySection: false
  hideStepTime: false
  hideScenarioKeyword: false
  hideTags: false
  errorMessageLength: 500
documentAttributes:
  docTitle: "Living Documentation"
  backend: "html5"
  docType: "book"
  toc: "right"
  icons: "font"
  tocLevels: 3
  sectAnchors: true
  sectLink: true
  docInfo: true
  pdfStyle:
  sourceHighlighter: "highlightjs"
  hardBreaks: true
  chapterLabel: "Chapter"
  versionLabel: "Version"