= Cukedoctor Extension module

image:https://www.versioneye.com/user/projects/55d3325f265ff6001c000425/badge.svg?style=flat[Dependency Status, link=https://www.versioneye.com/user/projects/55d3325f265ff6001c000425/]

This module extend cukedoctor generated documentation via http://asciidoctor.org/docs/asciidoctorj/#extension-api[Asciidoctor extensions mechanism^].

Cukedoctor comes with 5 extensions to enhance documentation content:

* *Filter extension* which lets features to be filtered using an input at top right of the page;

* *Minimizable extension* which lets you minimize/maximize features sections (minus/plus icon next to feature name);

* *Theme extension* to add theme support.

* *Footer* add cukedoctor footer.

* *Style* customizes asciidoctor stylesheet.

NOTE: All extensions target html documentation.

To disable extensions you can just clear the following system properties:

[source,java]
----
   System.setProperty("cukedoctor.disable.theme","anyValue");

   System.setProperty("cukedoctor.disable.filter","anyValue");

   System.setProperty("cukedoctor.disable.minmax","anyValue");

   System.setProperty("cukedoctor.disable.footer","anyValue");

   System.setProperty("cukedoctor.disable.style","anyValue");

----

NOTE: The value doesn't matter, if there is something in the system property the extension will be disabled.