= Cukedoctor Main module

image:https://www.versioneye.com/user/projects/55d33261265ff60022000290/badge.svg?style=flat[Dependency Status, link=https://www.versioneye.com/user/projects/55d33261265ff60022000290/]

This module brings the ability to execute cukedoctor converter as a Java main application (using command line: *java -jar*).

== Usage

This module  converts generated adoc files into html and pdf, here's an example:

[source, java]
----
@Test
public void shouldRenderHtmlForOneFeature(){
	CukedoctorMain main = new CukedoctorMain();
	main.execute(new String[]{
			"-o", "\"target/document-one\"", <1>
			"-p", "\"target/test-classes/json-output/one_passing_one_failing.json\"", <2>
			"-t", "Living Documentation", <3>
			"-f", "html", <4>
			"-toc", "left", <5>
                        "-numbering", "true" <6>
		});

	File generatedFile = FileUtil.loadFile("target/document-one.html");
	assertThat(generatedFile).exists();
	}
----
<1> output file name (default is 'documentation')
<2> path to cucumber json files (default is current dir)
<3> Document title (default is 'Living Documentation') 
<4> document format (Default is html)
<5> table of contents position (Default is right)
<6> Section numbering (Default is false)


Using in command line, the above test should be something like:

****
java -jar cukedoctor-main.jar -o "target/document-one" -p "target/test-classes/json-output/one_passing_one_failing.json"
							   -t "Living Documentation" -f html
****

== Disable extensions

You can disable https://github.com/rmpestano/cukedoctor/tree/master/cukedoctor-converter#disable-extensions[cukedoctor extensions^] by using _-D_ option when executing Cukedoctor main at command line:

----
java -jar -Dcukedoctor.disable.filter=123  -Dcukedoctor.disable.theme=abc cukedoctor-main-0.7.0.jar -p cucumber-output.json
----

You can download Cukedoctor main https://bintray.com/artifact/download/rmpestano/cukedoctor/com/github/cukedoctor/cukedoctor-main/0.7.0/cukedoctor-main-0.7.0.jar[jar here^]
