= Cukedoctor Main module

image:https://www.versioneye.com/user/projects/55d33261265ff60022000290/badge.svg?style=flat[Dependency Status, link=https://www.versioneye.com/user/projects/55d33261265ff60022000290/]

This module brings the ability to execute cukedoctor converter as a Java main application (using command line: *java -jar*).

== Usage

This module converts generated adoc files into html and pdf, here's an example:

[source, java]
----
@Test
public void shouldRenderHtmlForOneFeature(){
	CukedoctorMain main = new CukedoctorMain();
	main.execute(new String[]{
			"-o", "\"target/document-one\"", <1>
			"-p", "\"target/test-classes/json-output/one_passing_one_failing.json\"", <2>
			"-t", "Living Documentation", <3>
			"-f", "html", <4>
			"-toc", "left", <5>
            "-numbering", "true", <6>
            "-sourceHighlighter"
		});

	File generatedFile = FileUtil.loadFile("target/document-one.html");
	assertThat(generatedFile).exists();
	}
----
<1> output file name (default is 'documentation')
<2> path to cucumber json files or directory (default is current dir)
<3> Document title (default is 'Living Documentation') 
<4> document format (Default is html)
<5> table of contents position (Default is right)
<6> Section numbering (Default is false)

=== Command line

Using in command line, the above test should be something like:

----
java -jar cukedoctor-main.jar
		-o "target/document-one"
		-p "target/test-classes/json-output/one_passing_one_failing.json"
		-t "Living Documentation" -f html
		-hideSummarySection
		-hideScenarioKeyword
----

=== Maven exec plugin

You can use maven exec plugin, see example:

----
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>exec-maven-plugin</artifactId>
    <version>1.4.0</version>
    <configuration>
        <executable>java</executable>
        <arguments>
            <argument>-classpath</argument>
            <classpath />
            <argument>com.github.cukedoctor.CukedoctorMain</argument>
        </arguments>
    </configuration>
</plugin>
----

IMPORTANT: cukedoctor-main must be on your classpath

To invoke Cukedoctor just use:

----
mvn exec:exec
----

It will run with default args. To provide arguments, in this approach, you'll have a bit more work: http://stackoverflow.com/questions/15013651/using-maven-execexec-with-arguments[see here].


== Disable extensions

You can disable https://github.com/rmpestano/cukedoctor/tree/master/cukedoctor-extension#disable-extensions[cukedoctor extensions^] by using _-D_ option when executing Cukedoctor main at command line:

----
java -jar -Dcukedoctor.disable.filter=123  -Dcukedoctor.disable.theme=abc
		cukedoctor-main-1.0.6.jar
		-p cucumber-output.json
----

You can download Cukedoctor main https://bintray.com/artifact/download/rmpestano/cukedoctor/com/github/cukedoctor/cukedoctor-main/1.0.6/cukedoctor-main-1.0.6.jar[jar here^]

== Layout configuration

Some pieces of documentation can be hidden via configuration.

You can hide `Features` and `Summary` sections, as well as `scenario keyword` which prefixes each scenario and hide `tags` or `step time`. To do so just specify the following arg parameters respectively:

----
java -jar -Dcukedoctor.disable.filter=123  -Dcukedoctor.disable.theme=abc
		cukedoctor-main-1.0.6.jar
		-p cucumber-output.json
		-hideFeaturesSection <1>
		-hideSummarySection <2>
		-hideScenarioKeyword <3>
		-hideStepTime <4>
		-hideTags <5>
----
<1> Removes `Features` section so each feature is a section instead of a sub section of `Features`;
<2> Removes summary section
<3> Removes `scenario` keyword which prefixes each scenario;
<4> Removes step time calculation on each step;
<5> Removes tags rendering;
