= Cukedoctor Main module

This module brings the ability to execute cukedoctor reporter as a Java main application (using command line: *java -jar*).

== Usage

This module  converts generated adoc files into html and pdf, here's an example:

[source, java]
----
@Test
public void shouldRenderHtmlForOneFeature(){
	CukedoctorMain main = new CukedoctorMain();
	main.execute(new String[]{
			"-o", "\"target/document-one\"", <1>
			"-p", "\"target/test-classes/json-output/one_passing_one_failing.json\"", <2>
			"-t", "Living Documentation", <3>
			"-f", "html", <4>
			"-toc", "left", <5>
                        "-numbering", "true" <6>
		});

	File generatedFile = FileUtil.loadFile("target/document-one.html");
	assertThat(generatedFile).exists();
	}
----
<1> output file name (default is 'documentation')
<2> path to cucumber json files (default is current dir)
<3> Document title (default is 'Living Documentation') 
<4> document format (Default is html)
<5> table of contents position (Default is right)
<6> Section numbering (Default is false)


Using in command line, the above test should be something like:

****
java -jar cukedoctor-main.jar -o "target/document-one" -p "target/test-classes/json-output/one_passing_one_failing.json"
							   -t "Living Documentation" -f html
****

You can download Cukedoctor main https://bintray.com/artifact/download/rmpestano/cukedoctor/com/github/cukedoctor/cukedoctor-main/0.3.0/cukedoctor-main-0.3.0.jar[jar here^]
