= Cukedoctor maven plugin

image:https://www.versioneye.com/java/com.github.cukedoctor:cukedoctor-maven-plugin/badge.svg[Dependency Status, link=https://www.versioneye.com/java/com.github.cukedoctor:cukedoctor-maven-plugin/]


This module brings the ability to execute cukedoctor converter through a maven plugin.

The plugin just scans *.json* cucumber execution files in _target_ dir and generates asciidoc documentation on _target/cukedoctor_ folder.


== Usage

Just declare the plugin in your _pom.xml_:

[source, xml]
----
<plugin>
    <groupId>com.github.cukedoctor</groupId>
    <artifactId>cukedoctor-maven-plugin</artifactId>
    <version>0.6.0</version>
    <executions>
        <execution>
            <goals>
                <goal>execute</goal>
            </goals>
            <phase>install</phase> <1>
        </execution>
    </executions>
</plugin>
----
<1> You need to use a phase that runs after your tests, see https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html[maven lifecycle].

[IMPORTANT]
====
To generate cucumber .json output files just execute your tests with *json* formatter, example:

[source,java]
----
@RunWith(Cucumber.class)
@CucumberOptions(plugins = {"json:target/cucumber.json"} )
----
NOTE: *plugins* option replaced *format* option which was deprecated in newer cucumber versions.

====

== Example of configuration

[source, xml]
----
<plugin>
    <groupId>com.github.cukedoctor</groupId>
    <artifactId>cukedoctor-maven-plugin</artifactId>
    <version>0.6.0</version>
         <configuration>
            <outputFileName>documentation</outputFileName> <1>
            <outputDir>docs</outputDir> <2>
            <format>pdf</format> <3>
            <toc>left</toc> <4>
            <numbered>true</numbered> <5>
         </configuration>
        <executions>
            <execution>
                <goals>
                    <goal>execute</goal>
                </goals>
                <phase>verify</phase>
            </execution>
        </executions>
</plugin>
----
<1> documentation filename
<2> directory name (relative to /target) to generate documetation (default is _cukedoctor_)
<3> document format, default is html5
<4> table of content position, default is right
<5> section numbering, default is false

[NOTE]
====
You can also execute the plugin without building the project but make sure you already have cucumber json files in build dir.

----
mvn cukedoctor:execute
----
====
