= Cukedoctor maven plugin

image:https://www.versioneye.com/user/projects/55d33262265ff6001a000210/badge.svg?style=flat[Dependency Status, link=https://www.versioneye.com/user/projects/55d33262265ff6001a000210/]



This module brings the ability to execute cukedoctor converter through a maven plugin.

The plugin just scans *.json* cucumber execution files in _target_ dir and generates asciidoc documentation on _target/cukedoctor_ folder.


== Usage

Just declare the plugin in your _pom.xml_:

[source, xml]
----
<plugin>
    <groupId>com.github.cukedoctor</groupId>
    <artifactId>cukedoctor-maven-plugin</artifactId>
    <version>1.0.2</version>
    <executions>
        <execution>
            <goals>
                <goal>execute</goal>
            </goals>
            <phase>install</phase> <1>
        </execution>
    </executions>
</plugin>
----
<1> You need to use a phase that runs after your tests, see https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html[maven lifecycle].

[IMPORTANT]
====
To generate cucumber .json output files just execute your tests with *json* formatter, example:

[source,java]
----
@RunWith(Cucumber.class)
@CucumberOptions(plugin = {"json:target/cucumber.json"} )
----
NOTE: *plugin* option replaced *format* option which was deprecated in newer cucumber versions.

====

== Example of configuration

[source, xml]
----
<plugin>
    <groupId>com.github.cukedoctor</groupId>
    <artifactId>cukedoctor-maven-plugin</artifactId>
    <version>1.0.2</version>
         <configuration>
            <outputFileName>documentation</outputFileName> <1>
            <outputDir>docs</outputDir> <2>
            <format>pdf</format> <3>
            <toc>left</toc> <4>
            <numbered>true</numbered> <5>
            <docVersion>${project.version}</docVersion> <6>
         </configuration>
        <executions>
            <execution>
                <goals>
                    <goal>execute</goal>
                </goals>
                <phase>verify</phase>
            </execution>
        </executions>
</plugin>
----
<1> documentation filename
<2> directory name (relative to /target) to generate documetation (default is _cukedoctor_)
<3> document format, default is html5
<4> table of content position, default is right
<5> section numbering, default is false
<6> documentation version (http://asciidoctor.org/docs/user-manual/#revision-number-date-and-remark[asciidoctor revNumber^])

[NOTE]
====
You can also execute the plugin without building the project but make sure you already have cucumber json files in build dir.

----
mvn cukedoctor:execute
----
====

== Configuration options

.Supported plugin configuration
[cols="1m,3,1"]
|===
|Name |Description | Default

|outputFileName
|Generated documentation file name
|documentation

|outputDir
|Directory of where documentation will be saved
|${buildDir}/cukedoctor

|documentTitle
|Documentation title (first section)
|Living Documentation

|format
|Generated documetation format. Possible values: pdf, html, all
|html

|toc
|Table of contents position
|right

|numbered
|Section numbering
|true

|disableFilter
|Flag to disable filter
|

|disableMinimizable
|Flag to disable minimizable feature sections
|

|disableTheme
|Flag to disable theme support
|

|hideSummarySection
|When present, this flag hides 'Summary' section
|

|hideFeaturesSection
|When present, this flag hides 'Features' section
|

|===

== Disable extensions

You can disable https://github.com/rmpestano/cukedoctor/tree/master/cukedoctor-extension#disable-extensions[cukedoctor extensions^] using the following configuration in maven plugin:

[source,xml]
----
  <configuration>
       <outputFileName>documentation</outputFileName> <1>
       <outputDir>docs</outputDir>
       <format>all</format>
       <toc>left</toc> <4>
       <disableTheme>true</disableTheme>
       <disableFilter>true</disableFilter>
       <disableMinimizable>true</disableMinimizable>
       <disableStyle>true</disableStyle>
  </configuration>

----

NOTE: The value doesn't matter, if there is something in the attribute the extension will be disabled
